apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-assignment
spec:
  replicas: 3 # Load Balancing between 3 pods
  selector:
    matchLabels:
      app: kubernetes-assignment
  template:
    metadata:
      labels:
        app: kubernetes-assignment
    spec:
      containers:
        - name: kubernetes-assignment
          image: samuele2000/kubernetes_assignment:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "200m"
            limits:
              cpu: "500m"
