apiVersion: v1
kind: Service
metadata:
  name: kubernetes-assignment
spec:
  type: NodePort
  selector:
    app: kubernetes-assignment
  ports:
    - protocol: TCP
      port: 8080 # Internal port
      targetPort: 8080 # Port inside the container
      nodePort: 30080 # external port
