name: CI/CD Pipeline

on: # update dockerhub image on push or pull_request
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest # create ubuntu vm that handles building the new docker image and pushes it to dockerhub

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # load code from repo

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "8.0.405" # Use the .NET version of your project

      - name: Build Project
        run: dotnet build kubernetes_assignment/kubernetes_assignment.csproj --configuration Release

      - name: Run Unit Tests
        run: |
          mkdir -p TestResults
          dotnet test kubernetes_assignment.Tests/kubernetes_assignment.Tests.csproj --no-build --configuration Release --logger trx --results-directory TestResults
        continue-on-error: false # Stop pipeline if tests fail

      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: TestResults

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # sets up docker builder

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 # login to duckerhub
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4 # build and push to dockerhub
        with:
          context: ./kubernetes_assignment
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/kubernetes_assignment:latest
